name: Python application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Change to root directory
        run: cd ..

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest-cov codecov

      - name: Lint with flake8
        run: |
          flake8 --max-line-length=130 .

      - name: Run tests with coverage and JUnit report
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            set PYTHONPATH=.
            pytest --cov --junitxml=junit.xml -o junit_family=legacy
          else
            PYTHONPATH=. pytest --cov --junitxml=junit.xml -o junit_family=legacy
          fi
        shell: bash

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        if: ${{ runner.os == 'macOS' || runner.os == 'Windows' }}
        run: bash <(curl -s https://codecov.io/bash) -f coverage.xml || echo 'Codecov upload failed'

      - name: Check app starts
        run: |
          python downtime_adj_app.py --help 

      - name: List installed packages
        run: pip list

      - name: show current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          
