name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Cross-platform way to set PYTHONPATH
        python -c "import sys; print(sys.platform)"
        if [ \"$RUNNER_OS\" = \"Windows\" ]; then set PYTHONPATH=. && pytest; else PYTHONPATH=. pytest; fi
      shell: bash
